### ISSUE TITLE
Are there any plans for allowing a local version of CP optimizer to be used rather than docplex cloud

### ISSUE THREAD

**Issue by barguello** [IBMDecisionOptimization/docplex-doc#1]
I have a local version of IBM CP optimizer and cannot use the cloud-based CP optimizer.

Are there any plans to allow a local version of CP optimizer to be used?

**Comment by vlkong** [comment]
Hello,

You can use a local CP optimizer with CPLEX Optimization Studio 12.7.
Please refer to the documentation here for configuration: https://rawgit.com/IBMDecisionOptimization/docplex-doc/master/docs/cp/creating_model.html#cloud-or-local-solving

**Comment by barguello** [comment]
Thank you!
