### ISSUE TITLE
Is there a java version

### ISSUE THREAD

**Issue by churunfa** [IBMDecisionOptimization/docplex-doc#12]
Is there a java version

**Comment by vlkong** [comment]
Hello,

There is no java version of `docplex`.
However there are java API for cpoptimizer and CPLEX.
Please have a look at https://www.ibm.com/docs/en/icos/20.1.0?topic=cplex-java-reference-manual
and:
https://www.ibm.com/docs/en/icos/20.1.0?topic=optimizer-cp-java-api-reference-manual

**Comment by churunfa** [comment]
Thank you～
