### ISSUE TITLE
How to save a Gantt chart as .png from docplex.cp.utils_visu

### ISSUE THREAD

**Issue by maxcast29** [IBMDecisionOptimization/docplex-doc#4]
Hi everyone,

I'm currently working on a scheduling project with docplex using the CP optimizer.

I'm using the cp.utils_visu functions to create and display a gantt chart, which works great, but I would like to automatically save thig gantt as a .png file, and I don't see any 'savefig' function in utils_visu. 

Here is my code to create and display my gantt chart: 

```
import docplex.cp.utils_visu as visu

if msol and visu.is_visu_enabled():
    visu.timeline('Solution per orders')
    for l in dict_sorted_orders_by_line.keys():
        for order in dict_sorted_orders_by_line[l]:
            visu.sequence(name=str(order))
            for s in SKILLS:
                wt = msol.get_var_solution(wtasks[(order, s)])
                if wt.is_present() and (wt.get_end()-wt.get_start()>0):
                        wtname = compact_name(s.worker , 4)
                        visu.interval(wt,int(l), wtname)
    visu.show()
```

Do you have any idea how I could do it ?

Thanks for your help.

**Comment by ooudot** [comment]
Hello Maxime,
The module utils_visu is based on matplotlib (https://matplotlib.org/) and is provided just to give simple graphical output to some examples. The aim of docplex.cp is to help model and solve constraint programming problems, not to provide graphical functions.
If you want to have a customized graphical output, please use matplotlib or some other dedicated package. You may find what you need here for example: https://stackoverflow.com/questions/3695117/python-module-for-plotting-gantt-charts.

**Comment by maxcast29** [comment]
Thanks for your answer Olivier,

I finally used matplotlib to solve my problem, wasn’t a big deal, I was just curious if there was any way to do it directly from util_visu.

**Comment by yyucresco** [comment]
Hi, maxcast29! 

I edit 'utils_visu.py' file and add  plt.savefig arround line 965, just before the plt.show(). 

This works for me.
