### ISSUE TITLE
docs refers to docplex.mp.linear.Var which does not exist

### ISSUE THREAD

**Issue by Dr-Irv** [IBMDecisionOptimization/docplex-doc#5]
Version 2.20.204 of docplex removed the class `docplex.mp.linear.Var`  .  But that class appears throughout the docs 
See for example https://ibmdecisionoptimization.github.io/docplex-doc/mp/docplex.mp.model.html where it appears 33 times.  We had code that imported this class, and when our client upgraded docplex, the code broke.

Fix the docs or the code, please.

**Comment by PhilippeCouronne** [comment]
Class was moved to a separate file `docplex.mp.dvar.Var` . We'll fix the doc links. Thanks for reporting this.

**Comment by Dr-Irv** [comment]
@PhilippeCouronne The problem here is that removing `docplex.mp.linear.Var` breaks existing code.  

The second problem (which probably doesn't belong here) is that a CPLEX 20.1 installation installs an older version of `docplex`, and if you are using `conda`, you have to do an `rm` to get rid of it, so that conda will install the latest.

**Comment by PhilippeCouronne** [comment]
@Dr-Irv you mean it breaks imports? I'll add an import of Var in linear to keep old code compatibility.

I'll pass the second item to the appropriate persons. This has been a constant pain in support.

**Comment by Dr-Irv** [comment]
> @Dr-Irv you mean it breaks imports? I'll add an import of Var in linear to keep old code compatibility.

Yes.  We had code that did `from docplex.mp.linear import Var` and that code broke when the client installed v2.20.204 and we had tested with v2.19..202

**Comment by PhilippeCouronne** [comment]
Sorry, my bad. I mistakenly considered `Var` as an internal class; I am a bit curious as to why you'd need to import it, if that's not confidential.

**Comment by Dr-Irv** [comment]
> I am a bit curious as to why you'd need to import it, if that's not confidential.

We imported it due to using typing in our code.  We had a model that had variables, and wanted to collect a subset of variables, so wrote:
```
from docplex.mp.linear import Var

list_of_vars: List[Var] = []
```
