### ISSUE TITLE
how to output multi results of integar programming

### ISSUE THREAD

**Issue by weidongzhou1994** [IBMDecisionOptimization/docplex-doc#8]
as title, I want to choose the best result from multi results, how can I output multi results using docplex.

**Comment by PhilippeCouronne** [comment]
Can you elaborate on this?
CPLEX's purpose is to output one optimal solution to a constrained problem, so it is generally used to return _one_ solution.
However, if what you want is generate some  various solutions _around_ the optimum, you might have a look
at `Model.populate`. This smethods populates a solution pool and returns a set of solution: of course, only one of them is optimal, the others being non-optimal neighbouring variations.

Search for "populate" in
http://ibmdecisionoptimization.github.io/docplex-doc/mp/docplex.mp.model.html
